---
- name: Install Packages
  apt:
      state: present
      name:
        - git
        - acl # Needed for Ansible to work well with unprivileged user


- name: Git user
  user:
      name: git
      shell: /bin/bash


- name: Keys allowed to use git
  authorized_key:
      user: git
      state: present
      key: '{{ item }}'
  with_file:
      - ssh_keys/mansoor

- name: Create Repositories
  command: "{{ 'git init --bare  /home/git/repos/' + item + '.git' }}"
  become_user: git
  args:
    creates: "{{ '/home/git/repos/' + item + '.git/HEAD' }}"
  loop:
    - repo1
    - repo2
